In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
#   load train_data.csv
train_data = pd.read_csv('usb_df_train.csv')
train_data.head()
test_data = pd.read_csv('usb_df_test.csv')
test_data.head()

# drop NaN values
train_data = train_data.dropna()
test_data = test_data.dropna()

X_train=train_data["reviewText"]
y_train=train_data["rating_class"]
X_test=test_data["reviewText"]
y_test=test_data["rating_class"]

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words='english', max_features=1000)
X_train_vectors = vectorizer.fit_transform(X_train)
X_test_vectors = vectorizer.transform(X_test)

NAIVE BAYES


In [4]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

model_nb = MultinomialNB()
model_nb.fit(X_train_vectors, y_train)
predictions_nb = model_nb.predict(X_test_vectors)

print("Accuracy:", accuracy_score(y_test, predictions_nb))
#  give F1 score
from sklearn.metrics import f1_score
f1_score(y_test, predictions_nb, average='weighted')

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predictions_nb))

# print F1 scores of each
from sklearn.metrics import classification_report

print(classification_report(y_test, predictions_nb))


Accuracy: 0.7649880095923262
[[  0   0  54]
 [  0  19 139]
 [  0   3 619]]
              precision    recall  f1-score   support

     Average       0.00      0.00      0.00        54
         Bad       0.86      0.12      0.21       158
        Good       0.76      1.00      0.86       622

    accuracy                           0.76       834
   macro avg       0.54      0.37      0.36       834
weighted avg       0.73      0.76      0.68       834



C:\Users\lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classific

LOGISTIC REGRESSION

In [5]:
from sklearn.linear_model import LogisticRegression

model_lr = LogisticRegression(max_iter=1000)
model_lr.fit(X_train_vectors, y_train)
predictions_lr = model_lr.predict(X_test_vectors)

print("Accuracy:", accuracy_score(y_test, predictions_lr))
#  give F1 score
print(f1_score(y_test, predictions_lr, average='weighted'))

#  give confusion matrix
print(confusion_matrix(y_test, predictions_lr))

# print F1 scores of each
print(classification_report(y_test, predictions_lr))


Accuracy: 0.8105515587529976
0.7666345564209157
[[  0   8  46]
 [  0  66  92]
 [  0  12 610]]
              precision    recall  f1-score   support

     Average       0.00      0.00      0.00        54
         Bad       0.77      0.42      0.54       158
        Good       0.82      0.98      0.89       622

    accuracy                           0.81       834
   macro avg       0.53      0.47      0.48       834
weighted avg       0.75      0.81      0.77       834



C:\Users\lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classific

SUPPORT VECTOR MACHINE

In [6]:
from sklearn.svm import SVC

model_svm = SVC()
model_svm.fit(X_train_vectors, y_train)
predictions_svm = model_svm.predict(X_test_vectors)

print("Accuracy:", accuracy_score(y_test, predictions_svm))

#  give F1 score
f1_score(y_test, predictions_svm, average='weighted')

#  give confusion matrix
print(confusion_matrix(y_test, predictions_svm))

# print F1 scores of each
print(classification_report(y_test, predictions_svm))


Accuracy: 0.8009592326139089
[[  0   3  51]
 [  0  49 109]
 [  0   3 619]]
              precision    recall  f1-score   support

     Average       0.00      0.00      0.00        54
         Bad       0.89      0.31      0.46       158
        Good       0.79      1.00      0.88       622

    accuracy                           0.80       834
   macro avg       0.56      0.44      0.45       834
weighted avg       0.76      0.80      0.75       834



C:\Users\lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classific

RANDOM FOREST CLASSIFIER

In [8]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

model_rf = RandomForestClassifier(n_estimators=100, random_state=42)
model_rf.fit(X_train_vectors, y_train)
predictions_rf = model_rf.predict(X_test_vectors)

print("Accuracy:", accuracy_score(y_test, predictions_rf))

#  give F1 score
f1_score(y_test, predictions_rf, average='weighted')

#  give confusion matrix
print(confusion_matrix(y_test, predictions_rf))

# print F1 scores of each
print(classification_report(y_test, predictions_rf))




Accuracy: 0.7973621103117506
[[  0   4  50]
 [  0  54 104]
 [  0  11 611]]
              precision    recall  f1-score   support

     Average       0.00      0.00      0.00        54
         Bad       0.78      0.34      0.48       158
        Good       0.80      0.98      0.88       622

    accuracy                           0.80       834
   macro avg       0.53      0.44      0.45       834
weighted avg       0.74      0.80      0.75       834



C:\Users\lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classific

GBD For text classification


In [10]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report

# Initialize Gradient Boosting Classifier
model_gb = GradientBoostingClassifier(n_estimators=100, random_state=42)

# Train the model
model_gb.fit(X_train_vectors, y_train)

# Make predictions
predictions_gb = model_gb.predict(X_test_vectors)

# Calculate accuracy
accuracy_gb = accuracy_score(y_test, predictions_gb)
print("Accuracy:", accuracy_gb)

# Calculate F1 score
f1_score_gb = f1_score(y_test, predictions_gb, average='weighted')
print("F1 Score:", f1_score_gb)

# Confusion matrix
conf_matrix_gb = confusion_matrix(y_test, predictions_gb)
print("Confusion Matrix:")
print(conf_matrix_gb)

# Classification report
class_report_gb = classification_report(y_test, predictions_gb)
print("Classification Report:")
print(class_report_gb)


Accuracy: 0.7985611510791367
F1 Score: 0.7529966485964479
Confusion Matrix:
[[  0   6  48]
 [  2  58  98]
 [  2  12 608]]
Classification Report:
              precision    recall  f1-score   support

     Average       0.00      0.00      0.00        54
         Bad       0.76      0.37      0.50       158
        Good       0.81      0.98      0.88       622

    accuracy                           0.80       834
   macro avg       0.52      0.45      0.46       834
weighted avg       0.75      0.80      0.75       834

